<?php

namespace App\Helpers;

class QuranHelper
{
    public static $daftarSurat = [
        ['nomor' => 1, 'nama' => "Al-Fatihah", 'ayat' => 7, 'juz' => [1]],
        ['nomor' => 2, 'nama' => "Al-Baqarah", 'ayat' => 286, 'juz' => [1, 2, 3]],
        ['nomor' => 3, 'nama' => "Ali 'Imran", 'ayat' => 200, 'juz' => [3, 4]],
        ['nomor' => 4, 'nama' => "An-Nisa'", 'ayat' => 176, 'juz' => [4, 5, 6]],
        ['nomor' => 5, 'nama' => "Al-Ma'idah", 'ayat' => 120, 'juz' => [6, 7]],
        ['nomor' => 6, 'nama' => "Al-An'am", 'ayat' => 165, 'juz' => [7, 8]],
        ['nomor' => 7, 'nama' => "Al-A'raf", 'ayat' => 206, 'juz' => [8, 9]],
        ['nomor' => 8, 'nama' => "Al-Anfal", 'ayat' => 75, 'juz' => [9, 10]],
        ['nomor' => 9, 'nama' => "At-Taubah", 'ayat' => 129, 'juz' => [10, 11]],
        ['nomor' => 10, 'nama' => "Yunus", 'ayat' => 109, 'juz' => [11]],
        ['nomor' => 11, 'nama' => "Hud", 'ayat' => 123, 'juz' => [11, 12]],
        ['nomor' => 12, 'nama' => "Yusuf", 'ayat' => 111, 'juz' => [12, 13]],
        ['nomor' => 13, 'nama' => "Ar-Ra'd", 'ayat' => 43, 'juz' => [13]],
        ['nomor' => 14, 'nama' => "Ibrahim", 'ayat' => 52, 'juz' => [13]],
        ['nomor' => 15, 'nama' => "Al-Hijr", 'ayat' => 99, 'juz' => [14]],
        ['nomor' => 16, 'nama' => "An-Nahl", 'ayat' => 128, 'juz' => [14]],
        ['nomor' => 17, 'nama' => "Al-Isra'", 'ayat' => 111, 'juz' => [15]],
        ['nomor' => 18, 'nama' => "Al-Kahf", 'ayat' => 110, 'juz' => [15, 16]],
        ['nomor' => 19, 'nama' => "Maryam", 'ayat' => 98, 'juz' => [16]],
        ['nomor' => 20, 'nama' => "Taha", 'ayat' => 135, 'juz' => [16]],
        ['nomor' => 21, 'nama' => "Al-Anbiya'", 'ayat' => 112, 'juz' => [17]],
        ['nomor' => 22, 'nama' => "Al-Hajj", 'ayat' => 78, 'juz' => [17]],
        ['nomor' => 23, 'nama' => "Al-Mu'minun", 'ayat' => 118, 'juz' => [18]],
        ['nomor' => 24, 'nama' => "An-Nur", 'ayat' => 64, 'juz' => [18]],
        ['nomor' => 25, 'nama' => "Al-Furqan", 'ayat' => 77, 'juz' => [18, 19]],
        ['nomor' => 26, 'nama' => "Asy-Syu'ara'", 'ayat' => 227, 'juz' => [19]],
        ['nomor' => 27, 'nama' => "An-Naml", 'ayat' => 93, 'juz' => [19, 20]],
        ['nomor' => 28, 'nama' => "Al-Qasas", 'ayat' => 88, 'juz' => [20]],
        ['nomor' => 29, 'nama' => "Al-'Ankabut", 'ayat' => 69, 'juz' => [20, 21]],
        ['nomor' => 30, 'nama' => "Ar-Rum", 'ayat' => 60, 'juz' => [21]],
        ['nomor' => 31, 'nama' => "Luqman", 'ayat' => 34, 'juz' => [21]],
        ['nomor' => 32, 'nama' => "As-Sajdah", 'ayat' => 30, 'juz' => [21]],
        ['nomor' => 33, 'nama' => "Al-Ahzab", 'ayat' => 73, 'juz' => [21, 22]],
        ['nomor' => 34, 'nama' => "Saba'", 'ayat' => 54, 'juz' => [22]],
        ['nomor' => 35, 'nama' => "Fatir", 'ayat' => 45, 'juz' => [22]],
        ['nomor' => 36, 'nama' => "Ya Sin", 'ayat' => 83, 'juz' => [22, 23]],
        ['nomor' => 37, 'nama' => "As-Saffat", 'ayat' => 182, 'juz' => [23]],
        ['nomor' => 38, 'nama' => "Sad", 'ayat' => 88, 'juz' => [23]],
        ['nomor' => 39, 'nama' => "Az-Zumar", 'ayat' => 75, 'juz' => [23, 24]],
        ['nomor' => 40, 'nama' => "Gafir", 'ayat' => 85, 'juz' => [24]],
        ['nomor' => 41, 'nama' => "Fussilat", 'ayat' => 54, 'juz' => [24, 25]],
        ['nomor' => 42, 'nama' => "Asy-Syura", 'ayat' => 53, 'juz' => [25]],
        ['nomor' => 43, 'nama' => "Az-Zukhruf", 'ayat' => 89, 'juz' => [25]],
        ['nomor' => 44, 'nama' => "Ad-Dukhan", 'ayat' => 59, 'juz' => [25]],
        ['nomor' => 45, 'nama' => "Al-Jasiyah", 'ayat' => 37, 'juz' => [25]],
        ['nomor' => 46, 'nama' => "Al-Ahqaf", 'ayat' => 35, 'juz' => [26]],
        ['nomor' => 47, 'nama' => "Muhammad", 'ayat' => 38, 'juz' => [26]],
        ['nomor' => 48, 'nama' => "Al-Fath", 'ayat' => 29, 'juz' => [26]],
        ['nomor' => 49, 'nama' => "Al-Hujurat", 'ayat' => 18, 'juz' => [26]],
        ['nomor' => 50, 'nama' => "Qaf", 'ayat' => 45, 'juz' => [26]],
        ['nomor' => 51, 'nama' => "Az-Zariyat", 'ayat' => 60, 'juz' => [26, 27]],
        ['nomor' => 52, 'nama' => "At-Tur", 'ayat' => 49, 'juz' => [27]],
        ['nomor' => 53, 'nama' => "An-Najm", 'ayat' => 62, 'juz' => [27]],
        ['nomor' => 54, 'nama' => "Al-Qamar", 'ayat' => 55, 'juz' => [27]],
        ['nomor' => 55, 'nama' => "Ar-Rahman", 'ayat' => 78, 'juz' => [27]],
        ['nomor' => 56, 'nama' => "Al-Waqi'ah", 'ayat' => 96, 'juz' => [27]],
        ['nomor' => 57, 'nama' => "Al-Hadid", 'ayat' => 29, 'juz' => [27]],
        ['nomor' => 58, 'nama' => "Al-Mujadalah", 'ayat' => 22, 'juz' => [28]],
        ['nomor' => 59, 'nama' => "Al-Hasyr", 'ayat' => 24, 'juz' => [28]],
        ['nomor' => 60, 'nama' => "Al-Mumtahanah", 'ayat' => 13, 'juz' => [28]],
        ['nomor' => 61, 'nama' => "As-Saff", 'ayat' => 14, 'juz' => [28]],
        ['nomor' => 62, 'nama' => "Al-Jumu'ah", 'ayat' => 11, 'juz' => [28]],
        ['nomor' => 63, 'nama' => "Al-Munafiqun", 'ayat' => 11, 'juz' => [28]],
        ['nomor' => 64, 'nama' => "At-Tagabun", 'ayat' => 18, 'juz' => [28]],
        ['nomor' => 65, 'nama' => "At-Talaq", 'ayat' => 12, 'juz' => [28]],
        ['nomor' => 66, 'nama' => "At-Tahrim", 'ayat' => 12, 'juz' => [28]],
        ['nomor' => 67, 'nama' => "Al-Mulk", 'ayat' => 30, 'juz' => [29]],
        ['nomor' => 68, 'nama' => "Al-Qalam", 'ayat' => 52, 'juz' => [29]],
        ['nomor' => 69, 'nama' => "Al-Haqqah", 'ayat' => 52, 'juz' => [29]],
        ['nomor' => 70, 'nama' => "Al-Ma'arij", 'ayat' => 44, 'juz' => [29]],
        ['nomor' => 71, 'nama' => "Nuh", 'ayat' => 28, 'juz' => [29]],
        ['nomor' => 72, 'nama' => "Al-Jinn", 'ayat' => 28, 'juz' => [29]],
        ['nomor' => 73, 'nama' => "Al-Muzzammil", 'ayat' => 20, 'juz' => [29]],
        ['nomor' => 74, 'nama' => "Al-Muddassir", 'ayat' => 56, 'juz' => [29]],
        ['nomor' => 75, 'nama' => "Al-Qiyamah", 'ayat' => 40, 'juz' => [29]],
        ['nomor' => 76, 'nama' => "Al-Insan", 'ayat' => 31, 'juz' => [29]],
        ['nomor' => 77, 'nama' => "Al-Mursalat", 'ayat' => 50, 'juz' => [29]],
        ['nomor' => 78, 'nama' => "An-Naba'", 'ayat' => 40, 'juz' => [30]],
        ['nomor' => 79, 'nama' => "An-Nazi'at", 'ayat' => 46, 'juz' => [30]],
        ['nomor' => 80, 'nama' => "'Abasa", 'ayat' => 42, 'juz' => [30]],
        ['nomor' => 81, 'nama' => "At-Takwir", 'ayat' => 29, 'juz' => [30]],
        ['nomor' => 82, 'nama' => "Al-Infitar", 'ayat' => 19, 'juz' => [30]],
        ['nomor' => 83, 'nama' => "Al-Mutaffifin", 'ayat' => 36, 'juz' => [30]],
        ['nomor' => 84, 'nama' => "Al-Insyiqaq", 'ayat' => 25, 'juz' => [30]],
        ['nomor' => 85, 'nama' => "Al-Buruj", 'ayat' => 22, 'juz' => [30]],
        ['nomor' => 86, 'nama' => "At-Tariq", 'ayat' => 17, 'juz' => [30]],
        ['nomor' => 87, 'nama' => "Al-A'la", 'ayat' => 19, 'juz' => [30]],
        ['nomor' => 88, 'nama' => "Al-Gasiyah", 'ayat' => 26, 'juz' => [30]],
        ['nomor' => 89, 'nama' => "Al-Fajr", 'ayat' => 30, 'juz' => [30]],
        ['nomor' => 90, 'nama' => "Al-Balad", 'ayat' => 20, 'juz' => [30]],
        ['nomor' => 91, 'nama' => "Asy-Syams", 'ayat' => 15, 'juz' => [30]],
        ['nomor' => 92, 'nama' => "Al-Lail", 'ayat' => 21, 'juz' => [30]],
        ['nomor' => 93, 'nama' => "Ad-Duha", 'ayat' => 11, 'juz' => [30]],
        ['nomor' => 94, 'nama' => "Al-Insyirah", 'ayat' => 8, 'juz' => [30]],
        ['nomor' => 95, 'nama' => "At-Tin", 'ayat' => 8, 'juz' => [30]],
        ['nomor' => 96, 'nama' => "Al-'Alaq", 'ayat' => 19, 'juz' => [30]],
        ['nomor' => 97, 'nama' => "Al-Qadr", 'ayat' => 5, 'juz' => [30]],
        ['nomor' => 98, 'nama' => "Al-Bayyinah", 'ayat' => 8, 'juz' => [30]],
        ['nomor' => 99, 'nama' => "Az-Zalzalah", 'ayat' => 8, 'juz' => [30]],
        ['nomor' => 100, 'nama' => "Al-'Adiyat", 'ayat' => 11, 'juz' => [30]],
        ['nomor' => 101, 'nama' => "Al-Qari'ah", 'ayat' => 11, 'juz' => [30]],
        ['nomor' => 102, 'nama' => "At-Takasur", 'ayat' => 8, 'juz' => [30]],
        ['nomor' => 103, 'nama' => "Al-'Asr", 'ayat' => 3, 'juz' => [30]],
        ['nomor' => 104, 'nama' => "Al-Humazah", 'ayat' => 9, 'juz' => [30]],
        ['nomor' => 105, 'nama' => "Al-Fil", 'ayat' => 5, 'juz' => [30]],
        ['nomor' => 106, 'nama' => "Quraisy", 'ayat' => 4, 'juz' => [30]],
        ['nomor' => 107, 'nama' => "Al-Ma'un", 'ayat' => 7, 'juz' => [30]],
        ['nomor' => 108, 'nama' => "Al-Kausar", 'ayat' => 3, 'juz' => [30]],
        ['nomor' => 109, 'nama' => "Al-Kafirun", 'ayat' => 6, 'juz' => [30]],
        ['nomor' => 110, 'nama' => "An-Nasr", 'ayat' => 3, 'juz' => [30]],
        ['nomor' => 111, 'nama' => "Al-Lahab", 'ayat' => 5, 'juz' => [30]],
        ['nomor' => 112, 'nama' => "Al-Ikhlas", 'ayat' => 4, 'juz' => [30]],
        ['nomor' => 113, 'nama' => "Al-Falaq", 'ayat' => 5, 'juz' => [30]],
        ['nomor' => 114, 'nama' => "An-Nas", 'ayat' => 6, 'juz' => [30]],
    ];
}
